### ISSUE TITLE
Unit Testing Coverage

### ISSUE THREAD

**Issue by BFieguth** [CNM-University-of-Guelph/NASEM-Model-Python#131]
Unit testing remain incomplete for the package. More comprehensive unit testing should be written to reach our 95% coverage goal.

**Comment by BFieguth** [comment]
There seems to be an issue with the coverage report from pytest. Functions that are being tested are marked as missing in the report. At this point I can't determine why some functions are being detected but othes are not.

**Comment by BFieguth** [comment]
@davos-i Could you pull the unit_test_coverage branch and see if you're getting the same issue with the coverage. amino_acid_equations should be 100% coverage but shows 97% for me. This is how I'm generating the report:

```
pytest --cov --cov-report=html --ignore=tests/integration
```

**Comment by davos-i** [comment]
I'm getting 2 errors preventing tests from running on my end.
It seems the added `import tests.testing_helpers` is the problem, I think because the tests directory isn't set up as module? Does it work for you?

Here's a snippet of errors:
```
ERROR tests/nasem_unit_testing/test_nasem_equations.py
ERROR tests/wrapper_functions/test_wrapper_functions.py


tests/nasem_unit_testing/test_nasem_equations.py:8: in <module>
    import tests.testing_helpers as helper
E   ModuleNotFoundError: No module named 'tests'

tests/wrapper_functions/test_wrapper_functions.py:10: in <module>
    import tests.testing_helpers as helper
E   ModuleNotFoundError: No module named 'tests'
```

**Comment by BFieguth** [comment]
@davos-i It works fine on Linux but also crashes on Windows. Looks to be an issue with how the different OS handle the pythonpath variable. I can reproduce the error oin Linux by dropping the project root from pythonpath before running pytest.

The latest commit should fix this. It configures pytest to always include the project root in pythonpath, allowing us to import from the tests directory without error. Let me know if this fixes it on your end.

**Comment by davos-i** [comment]
Sweet that's working now.
But yes looks like 97% and 7 lines 'missing' for `amino_acid_equations.py`.

I found this useful to read just now: https://breadcrumbscollector.tech/how-to-use-code-coverage-in-python-with-pytest/

2 things I didn't know before:
1) you can view the report in the terminal without creating html by using `--cov-report term` or `--cov-report term-missing`. 
e.g. This shows the line numbers of 'missing' in the table. It seems to match the html report.
```
pytest --cov --ignore=tests/integration --cov-report term-missing
```

2) 'branch' testing is a different metric instead of the default 'statement' coverage and can be calculated with the `--cov-branch` flag. e.g. This shows the `amino_acid_requirements.py` as 93% with this metric and gives some additional lines that are flagged as 'partial' in yellow in the html report. 
```
pytest --cov --ignore=tests/integration --cov-report=html --cov-branch
```

Anyway, I think I found something useful:
Try changing the output value to something really wrong in the test here: 
https://github.com/CNM-University-of-Guelph/NASEM-Model-Python/blob/c07fbfab95ceb300f43b4dba7330d445454c020f/tests/nasem_unit_testing/amino_acid_test.json#L73-L77

Then, re-run pytest and it won't fail. It seems it skips over it. I then realised that `Abs_EAA2_g` is calculated in `execute_model.py` but never used. If I add a line in the execute model that has `print(Abs_EAA2_g)` then it seems to detect the test and run it, and it will fail with the incorrect output value added above. 

Not sure why it behaves like this though...

**Comment by davos-i** [comment]
Ok... now I can't replicate this last bit. Even with the `print(Abs_EAA2_g)` I can't get it to execute that test. I have a value of `output = 8888888244.54` and it still says all are passing.

**Comment by BFieguth** [comment]
Ahh I've had this issue with some other functions. calculate_Abs_EAA2_g is not in the __init__.py for the package. The test script catches this and prints an error message but it doen't get printed when running pytest, only when running the scripts directly.

**Comment by BFieguth** [comment]
The testing scripts use ```import  nasem dairy as nd``` to find and run the functions. ```execute_model.py``` imports each module from NASEM_equations directly so it can access functions not included in the package.

**Comment by davos-i** [comment]
Some are a mystery, but I found: 

Line 313-314: The `calculate_Body_AA_TP()` is duplicated in the code. Once in AA and once in gestation.

Line 515: Seems like the test is giving the function an empty dict?
https://github.com/CNM-University-of-Guelph/NASEM-Model-Python/blob/c07fbfab95ceb300f43b4dba7330d445454c020f/tests/nasem_unit_testing/amino_acid_test.json#L235-L239

**Comment by BFieguth** [comment]
That's my mistake, I forgot  to add the values when making the test. It's weird this did not fail. If you add the"_series" suffix as shown below the test will fail.

```
  {
      "Name": "calculate_Trg_Mlk_EAA_g",
      "Input": {"Trg_Mlk_AA_g_series": {}},
      "Output": 15.100000000000001
  },
```

Perhaps using a try except block is leading to this unexpected behaviour in the testing code. Passing a dict to calculate_Trg_Mlk_EAA_g should throw an error as a dict has no sum() method. I believe that the try block is just skipping this error. If we keep the try except block we should add more exception handling to these scripts to catch these errors. 

I forgot to add the "_series" tag to 3 of these tests which is why they were not covered. The tests were failing but we never see the error messages. Adding this gets the amino_acid_equations module to 100% line coverage!

**Comment by BFieguth** [comment]
@davos-i  I think we've gotten to the bottom of these issues. It seems that when functions are not showing in the coverage report there a few possible reasons.

1. The function is not included in ```__init__.py```
2. There is another function in ```__init__.py``` with the same name in a different module. In this case only the last version of the function to be imported will be tested
3. The input data is the wrong type, resulting in an error when the function runs (ex. passing a dict when a series is required).

Thanks for the help Dave! I'll go through and fix the tests and see if I can find any other weird issues. It's good to know that even if there are issues with the test script the coverage report is able to show what is actually working.
