### ISSUE TITLE
refactor double logical tests overwriting themselves

### ISSUE THREAD

**Issue by davos-i** [CNM-University-of-Guelph/NASEM-Model-Python#36]
Some functions follow same pattern as R code but their logic is difficult to follow and could probably be a simple if/else. They seem to have 2 conditions that could both return the same value with 1 default value if FALSE. 

Refactoring will help write tests and docs:
https://github.com/CNM-University-of-Guelph-dev/NASEM-Model-Python/blob/ceb891a9fbf8715d77ab277cd36c3d84e7cf9fa9/src/nasem_dairy/NASEM_equations/dev_nutrient_intakes.py#L21-L48

**Comment by BFieguth** [comment]
@davos-i Most uses of np.where were refactored to use if else statements in #121. For the ```calculate_Fd_*``` functions the issue is we are compairing a series of values and need to apply the conditional logic to each value individually. I haven't found an easier way to do this than with np.where, which is just an if else applied to an array.  

I did clean up this code when applying new styling so hopefully that improves clarity. All the unit testing works with the current implementation. Do you still feel we should refactor these?
